url : 'https://opensource-demo.orangehrmlive.com/web/index.php/auth/login'

dasboard_url : "https://opensource-demo.orangehrmlive.com/web/index.php/dashboard/index"

username : "Admin"
password : "admin123"

username_locator : 'username'
password_locator : 'password'

submitButton_locator : '//*[@id="app"]/div[1]/div/div[1]/div/div[2]/div[2]/form/div[3]/button'

logout_dropdown : '//*[@id="app"]/div[1]/div[1]/header/div[1]/div[2]/ul/li/span/p'

logout_button : 'Logout'

invalid_username : 'admin'
invalid_password : 'Invalid password'

invalid_alert : '//*[@id="app"]/div[1]/div/div[1]/div/div[2]/div[2]/div/div[1]/div[1]/p'

pim_tab : '//*[@id="app"]/div[1]/div[1]/aside/nav/div[2]/ul/li[2]/a'
add_button : '//*[@id="app"]/div[1]/div[2]/div[2]/div/div[2]/div[1]/button'
firstname_textbox : '//*[@id="app"]/div[1]/div[2]/div[2]/div/div/form/div[1]/div[2]/div[1]/div[1]/div/div/div[2]/div[1]/div[2]/input'
middlename_textbox : '//*[@id="app"]/div[1]/div[2]/div[2]/div/div/form/div[1]/div[2]/div[1]/div[1]/div/div/div[2]/div[2]/div[2]/input'
lastname_textbox : '//*[@id="app"]/div[1]/div[2]/div[2]/div/div/form/div[1]/div[2]/div[1]/div[1]/div/div/div[2]/div[3]/div[2]/input'
employee_id_textbox : '//*[@id="app"]/div[1]/div[2]/div[2]/div/div/form/div[1]/div[2]/div[1]/div[2]/div/div/div[2]/input'
save_button : '//*[@id="app"]/div[1]/div[2]/div[2]/div/div/form/div[2]/button[2]'
added_user_toast : '//*[@id="oxd-toaster_1"]'

edit_button : '//*[@id="app"]/div[1]/div[2]/div[2]/div/div[2]/div[3]/div/div[2]/div[1]/div/div[9]/div/button[2]'
edit_firstname_textbox : '//*[@id="app"]/div[1]/div[2]/div[2]/div/div/div/div[2]/div[1]/form/div[1]/div[1]/div/div/div[2]/div[1]/div[2]/input'
edit_middlename_textbox : '//*[@id="app"]/div[1]/div[2]/div[2]/div/div/div/div[2]/div[1]/form/div[1]/div[1]/div/div/div[2]/div[2]/div[2]/input'
edit_lastname_textbox : '//*[@id="app"]/div[1]/div[2]/div[2]/div/div/div/div[2]/div[1]/form/div[1]/div[1]/div/div/div[2]/div[3]/div[2]/input'
edit_employee_id_textbox : '//*[@id="app"]/div[1]/div[2]/div[2]/div/div/div/div[2]/div[1]/form/div[2]/div[1]/div[1]/div/div[2]/input'
edit_employee_details_save : '//*[@id="app"]/div[1]/div[2]/div[2]/div/div/div/div[2]/div[1]/form/div[5]/button'
edit_employee_toast : '//*[@id="oxd-toaster_1"]'

delete_user_button : '//*[@id="app"]/div[1]/div[2]/div[2]/div/div[2]/div[3]/div/div[2]/div[1]/div/div[9]/div/button[1]'
confirm_delete_button : '//*[@id="app"]/div[3]/div/div/div/div[3]/button[2]'
deleted_user_toast : '//*[@id="oxd-toaster_1"]'



admin_tab : '//*[@id="app"]/div[1]/div[1]/aside/nav/div[2]/ul/li[1]/a'
my_info_tab : '//*[@id="app"]/div[1]/div[1]/aside/nav/div[2]/ul/li[6]/a'
username_firstname : 'firstName'
username_lastname : 'lastName'
nickname : '//*[@id="app"]/div[1]/div[2]/div[2]/div/div/div/div[2]/div[1]/form/div[1]/div[2]/div/div/div[2]/input'
employee_id : '//*[@id="app"]/div[1]/div[2]/div[2]/div/div/div/div[2]/div[1]/form/div[2]/div[1]/div[1]/div/div[2]/input'
other_id : '//*[@id="app"]/div[1]/div[2]/div[2]/div/div/div/div[2]/div[1]/form/div[2]/div[1]/div[2]/div/div[2]/input'
license_number : '//*[@id="app"]/div[1]/div[2]/div[2]/div/div/div/div[2]/div[1]/form/div[2]/div[2]/div[1]/div/div[2]/input'
ssn_number : '//*[@id="app"]/div[1]/div[2]/div[2]/div/div/div/div[2]/div[1]/form/div[2]/div[3]/div[1]/div/div[2]/input'
sin_number : '//*[@id="app"]/div[1]/div[2]/div[2]/div/div/div/div[2]/div[1]/form/div[2]/div[3]/div[2]/div/div[2]/input'
nationality_dropdown : '//*[@id="app"]/div[1]/div[2]/div[2]/div/div/div/div[2]/div[1]/form/div[3]/div[1]/div[1]/div/div[2]/div/div/div[1]'
marital_status : '//*[@id="app"]/div[1]/div[2]/div[2]/div/div/div/div[2]/div[1]/form/div[3]/div[1]/div[2]/div/div[2]/div/div'

#url : 'https://opensource-demo.orangehrmlive.com/web/index.php/auth/login'
#username : 'Admin'
#password : 'admin123'
#
#invalid_username : 'Admin'
#invalid_password : 'Invalid password'
#
test_first_name : 'Sathish'
test_middle_name : 'R'
test_last_name : 'Kumar'
test_employee_id : 1260